#!/usr/bin/env bash
# outputing the subdomain, it's record type and it's destination

if [ $# -eq 1 ]
then
    domains="www.$1, lb-01.$1, web-01.$1, web-02.$1"

else
    domains="$2.$1"
fi
dig $domains | awk '/ANSWER SECTION:/ {getline; split($1, array, "."); printf"The subdomain %s is a %s record and points to %s\n", array[1], $4, $5}'

