#!/usr/bin/env bash
# installing nginx
sudo apt update
# installs nginx
sudo apt-get -y install nginx
# allow it run on port 80 which is 'Nginx HTTP'
sudo ufw allow 'Nginx HTTP'
# writes the text "Hellow World" to a file named index.html
# located in /var/www/html/ directory
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

destination_url="https://www.youtube.com"
nginx_config="/etc/nginx/sites-available/default"
sudo sed -i "/server_name _;/a \\
\\
        location /redirect_me { \\
                return 301 $destination_url; \\
        }" $nginx_config

sudo sed -i "/index index.html index.htm index.nginx-debian.html;/a \\
\\
        error_page 404 /404.html; \\
\\
        location = /404.html { \\
                internal; \\
                root /var/www/html; \\
        }" $nginx_config
        
sudo service nginx restart


# /var/www/html/ is a commonly used directory in 
# Unix-like operating systems, particularly in web server 
# configurations like Apache or Nginx. It serves as the default
#  root directory for web server content.