#!/usr/bin/env bash

destination_url="https://www.youtube.com"
nginx_config="/etc/nginx/sites-available/default"
sudo sed -i "/server_name _;/a \\
\\
        location /redirect_me { \\
                return 301 $destination_url; \\
        }" $nginx_config
          