#!/usr/bin/env bash
# bash script to install and configure HAproxy on lb-01 server

#install HAproxy
sudo apt-get update
sudo apt-get install haproxy

# create a backup of HAproxy configuration file
sudo cp /etc/haproxy/haproxy.cfg etc-haproxy-haproxy.cfg.backup

# configure HAproxy to send traffric to web-01 and web-02 servers
haproxy_confg=\
"
frontend frontman_frontend
        bind *:80
        mode http
        default_backend frontman_web

backend frontman_web
        balance roundrobin

        server 420698-web-01 100.26.233.141 check
        server 420698-web-02 100.25.2.227 check
"
echo "$haproxy_confg" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
