#!/usr/bin/env bash
# configure a load-balancing server

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy=1.8.\*

echo \
	"
frontend frontman_frontend
	bind *:80
	mode http
	default_backend frontman_web
backend frontman_web
	mode http
	balance roundrobin
	server 420698-web-01 100.26.233.141 check
	server 420698-web-02 100.25.2.227 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart