#!/usr/bin/env bash
# Displays Best School 10 times with while loop

i=0
while [ $i -lt 11 ]
do
    if [ $i -eq 9 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi

    ((i++))
done 